### PR TITLE
Change SDL header path

### PR DESCRIPTION
**Pull request by kuflower**

### CODE REVIEW

**Comment by indianakernick** [comment]
I don't understand why this fixes the error. I also don't understand why there was an error on macOS (I developed this on macOS). The changes you made didn't break the macOS build (I expected them to).

Do you know what's going on here? I'll try to investigate this.

**Comment by indianakernick** [comment]
The `FindSDL2.cmake` module locates the directory containing the headers. I thought it located a directory containing an `SDL2` which then contained the headers. It seems that macOS and linux compilers don't really mind my mistake but windows is different.

**Comment by kuflower** [comment]
@Kerndog73, thanks for checking. I think it depends on brew's system path configuration when installing sdl2. I failed to build on MacOS env initially before changing CMakeList.txt or the path of headers.

Here's the guide in FindSDL2.cmake.
```
50 # Note that the header path has changed from SDL2/SDL.h to just SDL.h
51 # This needed to change because "proper" SDL convention
52 # is #include "SDL.h", not <SDL2/SDL.h>. This is done for portability
53 # reasons because not all systems place things in SDL2/ (see FreeBSD).
```
According to the cmake file, it recommends to use "SDL.h" rather than <SDL.h>. I checked both representations build successfully but please check which one is more better for your project.

Thanks for providing such a nice pacman demo!

**Comment by indianakernick** [comment]
Well if `<SDL.h>` works on CI then I see no reason to change it to `"SDL.h"`.

> Thanks for providing such a nice pacman demo!

I'm glad you like it! 😀

**Pull request merged**
