### PR TITLE
Add Conan package manager

### PR DESCRIPTION
**Pull request by Hopobcn**
Add [conan](https://conan.io/) package manager to keep track of all dependencies.

These are the packages conan pulls from `conan-center` and `bintray`:
* `entt/3.0.0@skypjack/stable`
* `sdl2/2.0.9@bincrafters/stable`
* `glm/0.9.9.4@g-truc/stable`

I also modified `.travis.yml` to cover all major os (linux, osx, windows). But it's a bit unpolished.

In reality `entt-pacman` only depends on `entt`, `sdl2` and [simpleton](https://github.com/Kerndog73/Simpleton-Engine). In my master branch I have changes that also pull `simpleton` as a dependency instead of having the whole library in `entt-pacman`. 
I'm not sure if you also want these changes so I extracted the interesting commits into this branch.  

([simpleton](https://bintray.com/hopobcn/public/simpleton%3Ahopobcn) package)

### CODE REVIEW

**Comment by Hopobcn** [comment]
Ah regarding `GLM_FORCE_SILENT_WARNINGS`, Do yo still want me to add it? I don't remember seeing warnings from `glm`, maybe with 0.9.9.4 they went away?

**Comment by indianakernick** [comment]
I just did a quick test and it looks like glm suppresses warnings by default like it used it. I guess there's no need to define `GLM_FORCE_SILENT_WARNINGS` then. 

In `conanfile.py`, you wrote `packman` instead of `pacman`. 

It's probably best not to create a Conan package for Simpleton. It doesn't have a versioning system and I often make breaking changes to it so embedding it into the project is probably the best option. 

SDL 2.0.5 or later is required. There's actually an `#if` that checks the version and uses a workaround to support older versions but I'm planning on removing that and just requiring 2.0.5. Is there a way to put this information (`SDL_version >= 2.0.5`) into the build system? If 2.0.6 is installed then we can use that. If 2.0.4 is installed then we have to download 2.0.5.

Would you mind updating the README with the new build instructions?

**Comment by Hopobcn** [comment]
Right now we're selecting a specific version: `sdl2/2.0.9@bincrafters/stable`. If we want to select a version-range we should use `sdl2/[>2.0.5 <2.1.0]@bincrafters/stable`. But I think it is adviced to not use it in the dependencies because the search is performend in each of the remotes which can be a slow operation. Also packages that do not follow semver cannot use version-ranges (but I think sdl2 follows semver, so no worries).

I've tried locally and seems to work:
```
Version ranges solved
    Version range '>2.0.5 <2.1.0' required by 'conanfile.py (entt-pacman/1.0.0@None/None)' resolved to 'sdl2/2.0.9@bincrafters/stable'
```

**Comment by indianakernick** [comment]
I just tried the new build system and it seems to be less convenient than my batteries-included approach. If you already have Conan installed then it might be more convenient. I use Homebrew instead of Conan so downloading and building this thing with the new build system took quite a while. First, I had to download Conan (21.7MB). Then Conan downloaded a bunch of tiny files (which ain't too quick). Then there's this cmake_installer package (47.9MB). I don't even know what it's for.

I'm beginning to think that maybe this isn't the best idea. For those who *don't* use Conan, this project has gotten pretty annoying to clone and build. For those who *do* use Conan, there's one extra command to install the Conan packages (SDL2 and GLM are probably already installed in this case). Is that really an improvement?

I'm grateful for the time you've put into this but maybe it isn't right for me. I'm sorry.

**Comment by Hopobcn** [comment]
No worries. I understand imposing conan might be not ok for everyone. What conan adds is a cross-platform way of specify project version dependencies programatically. 

For instance, if the project depends on `sdl > 2.0.5`. With conan you can ensure that 2.0.6 will be used. Without conan, preprocessor guards have to be added to detect versions, because there's no guarantee that `apt` will get you the version you want. For instance:
* xeinal: 2.0.4
* xenial-updates: 2.0.4
* bionic: 2.0.8
* bionic-updates: 2.0.8

For me the biggest improvement of this pr is that `glm` library isn't a blob of files in `include/glm` but an external dependency you get with a package manager.

Regarding [cmake_installer](https://github.com/conan-community/conan-cmake-installer) this is a build_requirement I added to guarantee that the cmake version used to build entt-pacman will be 3.12 but this can be removed.

**Comment by indianakernick** [comment]
I don’t mind using the preprocessor to ensure that we’re using the right version. I’m using an SDL 2.0.5 feature in one place. SDL 2.0.4 (and maybe earlier but I’m not sure) is supported with a workaround. I don’t like forcing the user to use one package manager. An approach that’s better than the current system would be supporting every popular package manager out there (instead of just one) but that’s a lot of hassle for not much gain.

This isn’t really in the same league as EnTT. You wouldn’t download this, install it and update it. You just want to download and run.

I want the least amount of time and headaches between looking and this project on Github and running it locally. That’s why I have chosen to do things the way that I have done them.

I understand the benefits of package managers. I understand that this is “the better way” but in this case, it’s not appropriate.

**Pull request closed without merging**
